[project]
name = "youtube-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dependency-injector>=4.47.1",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.3",
]
